# We deliberately don't use travis's language=python option because
# we install miniconda and use conda to get python. Additionally, 
# Travis's auto-install of python doesn't work on osx images (see
# https://github.com/travis-ci/travis-ci/issues/4729).
language: generic

os:
  - linux
  - osx

# get a more recent version of osx than the default image
osx_image: xcode8.3

sudo: false

before_install:
  - export PATH="$HOME/miniconda/bin:$PATH"

jobs:
  include:
    - install: scripts/ci/install_examples
      script: scripts/ci/test_examples
      env:
      - GROUP=examples
      - PYTHON_VERSION=3.6
    - install: scripts/ci/install_unit
      script: scripts/ci/test_unit
      env:
      - GROUP=unit
      - PYTHON_VERSION=2.7
    - install: scripts/ci/install_unit
      script: scripts/ci/test_unit
      env:
      - GROUP=unit
      - PYTHON_VERSION=3.4
    - install: scripts/ci/install_unit
      script: scripts/ci/test_unit
      env:
      - GROUP=unit
      - PYTHON_VERSION=3.6

notifications:
  email: false
